analytics: {}
color:
  brandColors:
    - '#C0C8C8'
    - '#00D0C8'
    - '#707070'
    - '#00C8C8'
    - '#000000'
  brandStrength: 1
  lightness: 1
  rhythmicContrast: 1
  saturation: 1
cta: {}
layout_spectrum: 0.412162
name: topleft
opengraph: {}
purpose: []
typography_spectrum: 0.385135
